
/* DEFINES  */
#define NUM_COMPONENTS (49) // UI COMPONENT:: Max number of UI component

/*
  Enum mapping human-readable component names to the index of the ui component
  in ui_tab
*/
typedef enum component_ids {
  INVALID_MENU = -1,
  TEST_MENU = 0,
  DIALOG_NAME = 1,
  DIALOG_RELATION = 2,
  DIALOG_CONTENT = 3,
  DIALOG_BUTTON_BUY = 4,
  DIALOG_BUTTON_SELL = 5,
  DIALOG_BUTTON_ESTABLISH_TRADE_ROUTE = 6,
  TRADE_BUTTON_LISTING_0 = 7,
  TRADE_BUTTON_LISTING_1 = 8,
  TRADE_BUTTON_LISTING_2 = 9,
  TRADE_BUTTON_LISTING_3 = 10,
  TRADE_BUTTON_LISTING_4 = 11,
  TRADE_BUTTON_LISTING_5 = 12,
  TRADE_BUTTON_LISTING_6 = 13,
  TRADE_BUTTON_LISTING_7 = 14,
  TRADE_BUTTON_LISTING_8 = 15,
  EMBARK_PROMPT = 16,
  INTERACT_PROMPT = 17,
  SCHEDULED_TRADE_ROUTE_PROMPT = 18,
  STATUS_HEALTH = 19,
  STATUS_MONEY = 20,
  TRADE_BUTTON_MERCHANT_ITEM_0 = 21,
  TRADE_BUTTON_MERCHANT_ITEM_1 = 22,
  TRADE_BUTTON_MERCHANT_ITEM_2 = 23,
  TRADE_BUTTON_MERCHANT_ITEM_3 = 24,
  TRADE_BUTTON_MERCHANT_ITEM_4 = 25,
  TRADE_BUTTON_MERCHANT_ITEM_5 = 26,
  TRADE_BUTTON_MERCHANT_ITEM_6 = 27,
  TRADE_BUTTON_MERCHANT_ITEM_7 = 28,
  TRADE_BUTTON_MERCHANT_ITEM_8 = 29,
  TRADE_BUTTON_PLAYER_ITEM_0 = 30,
  TRADE_BUTTON_PLAYER_ITEM_1 = 31,
  TRADE_BUTTON_PLAYER_ITEM_2 = 32,
  TRADE_BUTTON_PLAYER_ITEM_3 = 33,
  TRADE_BUTTON_PLAYER_ITEM_4 = 34,
  TRADE_BUTTON_PLAYER_ITEM_5 = 35,
  TRADE_BUTTON_PLAYER_ITEM_6 = 36,
  TRADE_BUTTON_PLAYER_ITEM_7 = 37,
  TRADE_BUTTON_PLAYER_ITEM_8 = 38,
  TRADE_BUTTON_MERCHANT_ITEM_PAGE_UP = 39,
  TRADE_BUTTON_MERCHANT_ITEM_PAGE_DOWN = 40,
  TRADE_BUTTON_PLAYER_ITEM_PAGE_UP = 41,
  TRADE_BUTTON_PLAYER_ITEM_PAGE_DOWN = 42,
  TRADE_TEXT_ON_HOVER_ITEM = 43,
  TRADE_TEXT_MERCHANT_VALUE = 44,
  TRADE_TEXT_PLAYER_VALUE = 45,
  TRADE_BUTTON_TRADE = 46,
  TRADE_TEXT_EVENT_PROMPT = 47
  // Populate as more components are added
} UI_ID;

/* GLOBALS */
// Index: item id, Element: Item struct for that item id
extern UI_COMPONENT ui_tab[NUM_COMPONENTS];


/* UTILITIES  */
UI_COMPONENT *get_ui_component_by_ID(UI_ID ui_id);
