
/* DEFINES  */
#define NUM_COMPONENTS (167) // UI COMPONENT:: Max number of UI component

/*
  Enum mapping human-readable component names to the index of the ui component
  in ui_tab
*/
typedef enum component_ids {
  /*
    WARNING:
    Zero indexed. Make sure to update above define statment
    when adding more components.
  */
  INVALID_MENU = -1,
  TEST_MENU = 0,
  DIALOG_NAME = 1,
  DIALOG_RELATION = 2,
  DIALOG_CONTENT = 3,
  DIALOG_BUTTON_BUY = 4,
  DIALOG_BUTTON_SELL = 5,
  DIALOG_BUTTON_ESTABLISH_TRADE_ROUTE = 6,
  TRADE_BUTTON_LISTING_0 = 7,
  TRADE_BUTTON_LISTING_1 = 8,
  TRADE_BUTTON_LISTING_2 = 9,
  TRADE_BUTTON_LISTING_3 = 10,
  TRADE_BUTTON_LISTING_4 = 11,
  TRADE_BUTTON_LISTING_5 = 12,
  TRADE_BUTTON_LISTING_6 = 13,
  TRADE_BUTTON_LISTING_7 = 14,
  TRADE_BUTTON_LISTING_8 = 15,
  EMBARK_PROMPT = 16,
  INTERACT_PROMPT = 17,
  SCHEDULED_TRADE_ROUTE_PROMPT = 18,

  LIST_BUTTON_RIGHT = 19,
  LIST_BUTTON_LEFT = 20,
  LIST_ITEM = 21,
  MERCENARY_BUY_PROMPT = 37, // +16
  MERCENARY_AVAIL = 38,
  ADD_MERCENARY = 39,
  SUB_MERCENARY = 40,
  REASSIGN_MENU_TITLE = 41,
  MY_SHIP_MERC = 42,
  CONSOLE = 43,
  CONSOLE_CURSOR = 44,
  CONSOLE_WORLD_COORDS = 45,
  CONSOLE_INTRA_CHUNK_COORDS = 46,
  CONSOLE_CHUNK_COORDS = 47,
  CONSOLE_ERROR = 48,

  TRADE_BUTTON_MERCHANT_ITEM_0 = 49,
  TRADE_BUTTON_MERCHANT_ITEM_1 = 50,
  TRADE_BUTTON_MERCHANT_ITEM_2 = 51,
  TRADE_BUTTON_MERCHANT_ITEM_3 = 52,
  TRADE_BUTTON_MERCHANT_ITEM_4 = 53,
  TRADE_BUTTON_MERCHANT_ITEM_5 = 54,
  TRADE_BUTTON_MERCHANT_ITEM_6 = 55,
  TRADE_BUTTON_MERCHANT_ITEM_7 = 56,
  TRADE_BUTTON_MERCHANT_ITEM_8 = 57,
  TRADE_BUTTON_PLAYER_ITEM_0 = 58,
  TRADE_BUTTON_PLAYER_ITEM_1 = 59,
  TRADE_BUTTON_PLAYER_ITEM_2 = 60,
  TRADE_BUTTON_PLAYER_ITEM_3 = 61,
  TRADE_BUTTON_PLAYER_ITEM_4 = 62,
  TRADE_BUTTON_PLAYER_ITEM_5 = 63,
  TRADE_BUTTON_PLAYER_ITEM_6 = 64,
  TRADE_BUTTON_PLAYER_ITEM_7 = 65,
  TRADE_BUTTON_PLAYER_ITEM_8 = 66,
  TRADE_BUTTON_MERCHANT_ITEM_PAGE_UP = 67,
  TRADE_BUTTON_MERCHANT_ITEM_PAGE_DOWN = 68,
  TRADE_BUTTON_PLAYER_ITEM_PAGE_UP = 69,
  TRADE_BUTTON_PLAYER_ITEM_PAGE_DOWN = 70,
  TRADE_TEXT_ON_HOVER_ITEM = 71,
  TRADE_TEXT_MERCHANT_VALUE = 72,
  TRADE_TEXT_PLAYER_VALUE = 73,
  TRADE_BUTTON_TRADE = 74,
  TRADE_TEXT_EVENT_PROMPT = 75,

  CONTAINER_1_SLOTS = 76,
  CONTAINER_1_NEXT = 111, // +35
  CONTAINER_1_PREV = 112,
  CONTAINER_1_MOVE = 113,
  CONTAINER_2_SLOTS = 114,
  CONTAINER_2_NEXT = 149, // +35
  CONTAINER_2_PREV = 150,
  CONTAINER_2_MOVE = 151,
  NEW_GAME = 152,
  SAVE = 153,
  LOAD = 154,
  SAVE_CLOSE = 155,
  SAVE_PROMPT = 156,
  SAVE_INPUT = 157,
  SAVE_STATUS = 158,

  GENERAL_PROMPT_ON_SCREEN = 159,

  STATUS_HEALTH = 160,
  STATUS_COPPER_ICON = 161,
  STATUS_SILVER_ICON = 162,
  STATUS_GOLD_ICON = 163,
  STATUS_COPPER_TEXT = 164,
  STATUS_SILVER_TEXT = 165,
  STATUS_GOLD_TEXT = 166,
  // Populate as more components are added
} UI_ID;

/* GLOBALS */
// Index: item id, Element: Item struct for that item id
extern UI_COMPONENT ui_tab[NUM_COMPONENTS];


/* UTILITIES  */
UI_COMPONENT *get_ui_component_by_ID(UI_ID ui_id);
